
server:
  port: 8080


spring:
  application:
    name: Demo
    version: ${random.long}
  profiles:
    active: dev

number: 2

#url: devUrl
#name: lg
#Dbname: jdbc:mysql://127.0.0.1:3306/test
#
#
#feign:
#  dmId: dm
#  gspId: geoserverplus
#  gspurl: ~
#  hystrix:
#    enabled: true #feign开启hystrix支持
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#ribbon:
#  ReadTimeout: 15000
#  ConnectTimeout: 15000
#  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试
#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.4.47:28761/eureka/


